## JOBS
---
jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: source
    trigger: true
#  - put: version
#    params:
#      bump: patch
  - task: mvn_build
    file: source/ci/tasks/mvn_build.yml

resource_types:
- name: semver-gitskipssl
  type: docker-image
  source:
    repository: maven
    tag: '3.3-jdk-8'
resources:
- name: source
  type: git
  source:
    uri: https://github.com/bluebossa63/guestbook2.0.git
    skip_ssl_verification: true
    branch: master
    username: {{gitlab-username}}
    password: {{gitlab-password}}
#- name: version
#  type: semver-gitskipssl
#  source:
#    driver: git
#    uri: https://github.com/bluebossa63/guestbook2.0.git
#    branch: version
#    username: {{gitlab-username}}
#    password: {{gitlab-password}}
#    file: version

#platform: linux

#image_resource:
#  type: docker-image
#  source:
#    repository: airhacks/wildfly 
#
#inputs:
#  name: guestbook2.0

#run:
#  path: ./guestbook2.9/ci/build.sh

#image_resource:
#  type: docker-image
#  source:
#    repository: maven
#    tag: '3.3-jdk-8'

#inputs:
#- name: guestbook2.0 

#run:
#  path: ./guestbook2.0/ci/test.sh
