## JOBS
---
jobs:
- name: build
  public: true
  serial: true
  plan:
  - get: source
    trigger: true
  - task: mvn_build
    file: source/ci/tasks/mvn_build.yml
  - put: docker-hub
    params:
      build: source
      tag_as_latest: true
      
resource_types:
- name: semver-gitskipssl
  type: docker-image
  source:
    repository: bluebossa63/test
    
resources:
- name: source
  type: git
  source:
    uri: https://github.com/bluebossa63/guestbook2.0.git
    skip_ssl_verification: true
    branch: master
    username: {{gitlab-username}}
    password: {{gitlab-password}}
    
- name: docker-hub
  type: docker-image
  source:
    repository: bluebossa63/test
    email: {{gitlab-email}}
    username: {{gitlab-username}}
    password: {{gitlab-password}}
